yooongjun/moassu-backend

.gitignore, build.gradle
[변경 사항]
build.gradle 파일에 MySQL 의존성 추가
.gitignore 파일에 민감정보 파일 추가 ( application.properties)
[설명]
MySQL을 프로젝트에 추가하기 위해 build.gradle 파일에 의존성을 추가하였습니다. 
또한 민감정보 파일들을 .gitignore 파일에 추가하여 원격 저장소에 올라가지 않도록 설정하였습니다.
=> Add MySQL dependency and update gitignore file

.gitignore, build.gradle, src/main/resources/application.properties
Refactor MySQL dependency, separate sensitive information, update gitignore and application properties
- Remove implementation 'mysql:mysql-connector-java' and add runtimeOnly 'mysql:mysql-connector-java' to build.gradle
- Add application-db.properties to separate sensitive information from application.properties
- Update application.properties with MySQL driver configuration and URL
- Update .gitignore to ignore application-db.properties
=> Refactor MySQL dependency, separate sensitive information, update gitignore and application properties

src/main/java/com/ssu/moassubackend/config/WebMvcConfig.java
=> config cors

build.gradle, src/main/java/com/ssu/moassubackend/MoassuBackendApplication.java, src/main/java/com/ssu/moassubackend/test/Dummy.java, src/main/java/com/ssu/moassubackend/test/SseEmitters.java, src/main/java/com/ssu/moassubackend/test/TestController.java
=> :white_check_mark: update test api

build.gradle, src/main/java/com/ssu/moassubackend/config/SwaggerConfiguration.java
Add Swagger, validation dependencies and SwaggerConfiguration
=> Add Swagger, validation dependencies and SwaggerConfiguration

src/main/java/com/ssu/moassubackend/domain/post/Fun.java, src/main/java/com/ssu/moassubackend/domain/post/Homepage.java, src/main/java/com/ssu/moassubackend/domain/post/Instagram.java, src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/domain/post/Status.java
- create post entity
- create Instagram entity
- create Fun entity
- create Homepage entity
- Instagram => From Instagram
- Fun => From Funsystem
- Homepage => From Department Homepage
=> Create Post entity

src/main/java/com/ssu/moassubackend/domain/post/Unipage.java
=> :card_file_box: create unipage class

src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/domain/post/Unipage.java
- add unipage class constructor
=> :card_file_box: add unipage class constructor

build.gradle
- add jython to configuration file
=> :wrench: add jython to gradle file

build.gradle, src/main/java/com/ssu/moassubackend/scrap/ScrapHomepageUniv.java
- add build.gradle
- add ScrapHomepageUniv class
=> add build.gradle

src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/domain/post/Unipage.java, src/main/java/com/ssu/moassubackend/post/repository/PostRepository.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/ScrapHomepageUniv.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageUnivDto.java
- Post 의 content type 변경
- Unipage의 img_url, img_name 타입 변경
- Post의 ImageUrl을 저장할 새로운 table 추가 고려 필요.
=> Save data in DB from homepage_univ.json 

src/main/java/com/ssu/moassubackend/domain/image/Image.java, src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/domain/post/Unipage.java, src/main/java/com/ssu/moassubackend/post/image/repository/ImageRepository.java, src/main/java/com/ssu/moassubackend/post/image/service/ImageService.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java
- Image entity 클래스 생성
- homepage_univ.json 저장 기능 수정
=> Create Image entity class

src/main/java/com/ssu/moassubackend/MoassuBackendApplication.java, src/main/java/com/ssu/moassubackend/scrap/ScrapHomepageUniv.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java
- flask 서버에서 보낸 데이터를 받는 컨트롤러 함수 생성
- 해당 컨트롤러는 학교 홈페이지 데이터를 받음.
=> Get data list from flask server

src/main/java/com/ssu/moassubackend/domain/post/Homepage.java, src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/domain/post/Unipage.java, src/main/java/com/ssu/moassubackend/post/PostController.java, src/main/java/com/ssu/moassubackend/post/dto/response/UnivDetailDto.java, src/main/java/com/ssu/moassubackend/post/dto/response/UnivListDto.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/ScrapHomepageUniv.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageAiDto.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageElecDto.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageGmDto.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageSoftDto.java
=> :sparkles: Create univ controller

src/main/java/com/ssu/moassubackend/post/PostController.java, src/main/java/com/ssu/moassubackend/post/dto/response/HomepageDetailDto.java, src/main/java/com/ssu/moassubackend/post/dto/response/UnivListDto.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java
- create department controller
=> :sparkles: Create department list controller

src/main/java/com/ssu/moassubackend/post/service/PostService.java
=> :bug: Fix univ homepage Localdate

src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java
=> :art: Fix univ homepage dto

src/main/java/com/ssu/moassubackend/domain/post/Fun.java, src/main/java/com/ssu/moassubackend/domain/post/Instagram.java, src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/post/PostController.java, src/main/java/com/ssu/moassubackend/post/dto/response/FunListDto.java, src/main/java/com/ssu/moassubackend/post/dto/response/InstaListDto.java, src/main/java/com/ssu/moassubackend/post/dto/response/UnivListDto.java, src/main/java/com/ssu/moassubackend/post/repository/InstagramRepository.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageFunDto.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageInstaDto.java
- Create fun, instagram save api
- Create fun, instagram paging api
=> :sparkles: Create fun, instagram api

src/main/java/com/ssu/moassubackend/post/PostController.java
=> :bug: Fix fun, instagram api

src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageInstaDto.java, src/main/resources/application.properties
-  Fix instagram api
-  Fix instagram dto
=> :bug: Fix instagram api

src/main/java/com/ssu/moassubackend/domain/post/Fun.java, src/main/java/com/ssu/moassubackend/domain/post/Post.java, src/main/java/com/ssu/moassubackend/post/PostController.java, src/main/java/com/ssu/moassubackend/post/dto/response/FunListDto.java, src/main/java/com/ssu/moassubackend/post/dto/response/UnivListDto.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageFunDto.java
- Fix Post DB
- Fix Fun DB
- Fix Scraping LocalDate convert method
=> :bug: Fix Post DB

src/main/java/com/ssu/moassubackend/post/PostController.java, src/main/java/com/ssu/moassubackend/post/repository/FunRepository.java, src/main/java/com/ssu/moassubackend/post/repository/HomepageRepository.java, src/main/java/com/ssu/moassubackend/post/repository/PostRepository.java, src/main/java/com/ssu/moassubackend/post/repository/UnipageRepository.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/ScrapHomepageUniv.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java, src/main/resources/application.properties
- fix scrap api
- fix post api
- add response header about totalpages
=> :bug: Fix scraping, posts

src/main/java/com/ssu/moassubackend/post/service/PostService.java
- Fix post's LocalDate convert Method
=> :bug: Fix post's LocalDate convert Method

src/main/java/com/ssu/moassubackend/post/dto/response/UnivListDto.java
=> :bug: Fix univ_page response dto

src/main/java/com/ssu/moassubackend/domain/post/Instagram.java, src/main/java/com/ssu/moassubackend/post/dto/response/InstaListDto.java, src/main/java/com/ssu/moassubackend/post/service/PostService.java, src/main/java/com/ssu/moassubackend/scrap/controller/ScrapController.java, src/main/java/com/ssu/moassubackend/scrap/dto/HomepageInstaDto.java
add title to instagram instead of image
=> :sparkles: add title to instagram instead of image
